### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by ghost** [volosoft/lepton-theme#13]
Hello,

- There is an issue with RTL, when changing the language to Arabic the configs in the sidebar became hidden.

thanx.

**Comment by ismcagdas** [comment]
RTL support is not released yet, we are planning to release it in 2 weeks.

**Comment by ghost** [comment]
Hello, @ismcagdas  Any update on this?

**Comment by ismcagdas** [comment]
RTL feature is being tested at the moment. I hope we will merge it to our release branch in a few days.

**Comment by ghost** [comment]
Hello @ismcagdas, has this been merged?

**Comment by ismcagdas** [comment]
@Moahammedalqaisi yes this is released. You can download a new ABP template (commercial or open source) and it should support RTL.
