### ISSUE TITLE
MIME-type error after migrating to LeptonX Lite Angular UI

### ISSUE THREAD

**Issue by lukagalovic** [volosoft/lepton-theme#15]
After migrating to LeptonX Angular UI, I am getting following error in browser and UI doesnt load.

"Refused to apply style from 'http://localhost:4200/bootstrap-dim.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
"

**Comment by ismcagdas** [comment]
@ipcheGevara could you share your angular.json file ?

**Comment by lukagalovic** [comment]
This solved my problem: 
https://github.com/abpframework/abp/blob/rel-6.0/docs/en/UI/Angular/Theme-Configurations.md

After updating angular.json file following instructions from above link, site loads.
