### ISSUE TITLE
On LeptopXLite theme on Angular, how to make the sidebar closed by default?

### ISSUE THREAD

**Issue by idreeshaddad** [volosoft/lepton-theme#23]
![image](https://github.com/volosoft/lepton-theme/assets/2285974/ff249473-b26d-428e-8d43-fe54008eb86c)

The Sidebar is open by default, is there a way to change its behavior and make it closed by default?

[The question on StackOverflow](https://stackoverflow.com/questions/77604985/in-abp-io-leptopxlite-theme-on-angular-how-to-make-the-sidebar-closed-by-defaul)

**Comment by ismcagdas** [comment]
@masumulu28 is this possible ?

**Comment by idreeshaddad** [comment]
For what it's worth, I made it work with a walkaround. I triggered the click event on the button. 
And Here is the code for your reference:

``` TS
export class AppComponent implements AfterViewInit {

  constructor(private el: ElementRef) { }

  ngAfterViewInit() {
    
    const element = this.el.nativeElement.querySelector('.menu-collapse-icon');

    if (element) {
      element.click();
    }
  }
}
```

**Comment by masum-ulu** [comment]
Hi,
You can use `LayoutService` from `@volo/ngx-lepton-x.core` pacakge

## Example

```ts
import { Component, inject } from '@angular/core';
import { LayoutService } from '@volo/ngx-lepton-x.core';

@Component({
  selector: 'app-root',
  template: `
    <abp-loader-bar></abp-loader-bar>
    <abp-dynamic-layout></abp-dynamic-layout>
    <abp-gdpr-cookie-consent></abp-gdpr-cookie-consent>
  `,
})
export class AppComponent {
  protected readonly layoutService = inject(LayoutService);
  constructor() {
    this.layoutService.addClass('hover-trigger')
  }
}
```

**Comment by idreeshaddad** [comment]
@masumulu28 It works.
Maybe it's best if it is exposed as a configuration parameter in future updates.
Thank you.
