### ISSUE TITLE
Npm dependencies package `@abp/aspnetcore.mvc.ui.theme.shared` version not changed

### ISSUE THREAD

**Issue by JadynWong** [volosoft/lepton-theme#24]
The npm package `@abp/aspnetcore.mvc.ui.theme.leptonxlite` depends on the `@abp/aspnetcore.mvc.ui.theme.shared` package, but its version has remained at v7.2.1 since version v2.2.0. 

While this is not a problem, it is not consistent with abp's strategy for other npm packages. Is it possible to use the same dependency version update policy for future releases?

https://www.npmjs.com/package/@abp/aspnetcore.mvc.ui.theme.leptonxlite/v/3.0.1?activeTab=code

https://www.npmjs.com/package/@abp/aspnetcore.mvc.ui.theme.leptonxlite/v/2.2.0?activeTab=code

https://github.com/abpframework/abp/blob/dev/npm/packs/aspnetcore.mvc.ui.theme.basic/package.json

**Comment by masum-ulu** [comment]
Hello, 

We've created an internal issue for this problem, We'll update all `@abp` and `@volo` aspnet-core npm packages version. we'll comply version matrix thank you
