### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by cbogner85** [volosoft/lepton-theme#5]
Hello,

I'm very excited about leptonx since its first announcement. 

As there has not been a code update since the first alpha version (released in August), could you please give us an update regarding the project status/ release date? Is it still on track to be released "just after ABP 5.0 final" (which has been published last week)? And additionally, will 1.0 stable include support for MVC?

Thanks and best regards
Claus

**Comment by cellero** [comment]
Where do I go to see progress on Lepton X?  
It seems the project keeps being delayed without updating the community.  
We are waiting on Lepton X for a new project.

**Comment by ismcagdas** [comment]
@cellero there are still several items in the beta-1 milestone. We expect to complete them in 2 weeks. After that, we are planning to release a beta verison for LeptonX.

**Comment by cellero** [comment]
Good day @ismcagdas , just checking in for an update on LeptonX.  Are we getting closer to a release?

Thank you

**Comment by ismcagdas** [comment]
@cellero all the items for beta1 is completed. We are planning to release beta1 version in 1-2 days.

**Comment by julian-forster** [comment]
i'm so looking forward to it :)

**Comment by cbogner85** [comment]
@ismcagdas  It seems beta1 for angular is now available on npm, when will mvc be available and where do we get installation instructions?  :)

**Comment by ismcagdas** [comment]
NuGet packages are also published but we are testing migration documents at the moment. Docs will be on docs.abp.io in 1-2 days. Do you want to use open source or commercial version ? I can share related docs here with you.

**Comment by cbogner85** [comment]
Awesome! I'm so excited about it :) 
I'm using abp commercial  :)

**Comment by ismcagdas** [comment]
Here is the draft document https://github.com/abpio/abp-commercial-docs/blob/docs/lpx/en/themes/lepton-x/commercial/mvc.md.

**Comment by cbogner85** [comment]
Thank you very much @ismcagdas. It's so easy to switch the theme... great work guys!

**Comment by ismcagdas** [comment]
Let me know if it works or not :) So I will try to help you further.

**Comment by julian-forster** [comment]
Can you please send the draft document for abp framework too?

**Comment by ismcagdas** [comment]
@JulianForster01 sure, those are placed here https://github.com/abpio/abp-commercial-docs/tree/docs/lpx/en/themes/lepton-x/lite

**Comment by julian-forster** [comment]
Thank you very much!!

**Comment by cbogner85** [comment]
@ismcagdas  it works great and looks really nice! now i have some work to adapt my changes to the new theme :)

**Comment by cellero** [comment]
I have followed the MVC instructions successfully, but have been unsuccessful for Blazor UI (both server and wasm).

Can you confirm that Blazor UI works in the beta release as per these instructions:
https://github.com/abpio/abp-commercial-docs/blob/docs/lpx/en/themes/lepton-x/commercial/blazor.md

I have followed the instructions and it does not render.

**Comment by cellero** [comment]
Is the Blazor UI documentation correct?
https://github.com/abpio/abp-commercial-docs/blob/docs/lpx/en/themes/lepton-x/commercial/blazor.md

I have tried but cannot get the Blazor UI working correctly.  
MVC UI works ok.

**Comment by ismcagdas** [comment]
@cellero for Blazor, our team is updating the documentation. That's why we didn't publish those documents yet 🙂. I will inform you once the documents are updated.

**Comment by tobimax** [comment]
Hi, is there an update for blazor support?

**Comment by ismcagdas** [comment]
Closing the issue for now. @tobimax Blazor support is added, you can check its [documentation](https://docs.abp.io/en/abp/6.0/Themes/LeptonXLite/Blazor)
